-- =============================================================================
-- Vokabeltrainer – initial schema
--
-- Tables:   public.vocabulary, public.learning_events
-- Function: public.record_answer(...)  (atomic answer recording, idempotent)
--
-- Security model:
--   * Every row belongs to exactly one auth user (user_id).
--   * RLS is enabled on every table; policies only allow access to rows where
--     user_id = auth.uid() for the role "authenticated".
--   * The anon role has no table privileges at all.
--   * record_answer runs as SECURITY INVOKER, so RLS applies inside it as well.
--
-- Run once in the Supabase SQL editor or via `supabase db push`.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- Helper: keep updated_at current
-- -----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;


-- -----------------------------------------------------------------------------
-- Table: vocabulary
-- -----------------------------------------------------------------------------
create table public.vocabulary (
  id uuid primary key default gen_random_uuid(),

  -- Defaults to the caller; the insert policy additionally enforces it.
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,

  source_language text not null check (char_length(btrim(source_language)) between 1 and 50),
  target_language text not null check (char_length(btrim(target_language)) between 1 and 50),

  question text not null check (char_length(btrim(question)) between 1 and 500),
  answer   text not null check (char_length(btrim(answer))   between 1 and 500),

  correct_count   integer not null default 0 check (correct_count >= 0),
  incorrect_count integer not null default 0 check (incorrect_count >= 0),

  last_asked_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Needed for the composite foreign key from learning_events, which guarantees
  -- that an event can only reference a vocabulary row of the same user.
  constraint vocabulary_id_user_id_key unique (id, user_id)
);

comment on table public.vocabulary is 'Vocabulary entries of a user including aggregated learning statistics.';

create index vocabulary_user_id_created_at_idx on public.vocabulary (user_id, created_at desc);
create index vocabulary_user_id_last_asked_at_idx on public.vocabulary (user_id, last_asked_at desc);

create trigger vocabulary_set_updated_at
  before update on public.vocabulary
  for each row execute function public.set_updated_at();


-- -----------------------------------------------------------------------------
-- Table: learning_events (append-only answer history)
-- Basis for later features: learning curves, daily stats, streaks, SM-2, ...
-- -----------------------------------------------------------------------------
create table public.learning_events (
  -- Generated by the client so that retries (e.g. after a network failure)
  -- are idempotent: the same answer is never counted twice.
  id uuid primary key default gen_random_uuid(),

  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  vocabulary_id uuid not null,
  was_correct boolean not null,
  created_at timestamptz not null default now(),

  constraint learning_events_vocabulary_fkey
    foreign key (vocabulary_id, user_id)
    references public.vocabulary (id, user_id)
    on delete cascade
);

comment on table public.learning_events is 'One row per answered flashcard. Append-only.';

create index learning_events_user_id_created_at_idx on public.learning_events (user_id, created_at desc);
create index learning_events_vocabulary_id_idx on public.learning_events (vocabulary_id);


-- -----------------------------------------------------------------------------
-- Privileges: nothing for anon, CRUD for authenticated (further limited by RLS)
-- -----------------------------------------------------------------------------
revoke all on table public.vocabulary from anon;
revoke all on table public.learning_events from anon;

grant select, insert, update, delete on table public.vocabulary to authenticated;
-- learning_events is append-only from the client's perspective: no UPDATE.
revoke update on table public.learning_events from authenticated;
grant select, insert, delete on table public.learning_events to authenticated;


-- -----------------------------------------------------------------------------
-- Row Level Security
-- (select auth.uid()) is used instead of auth.uid() so Postgres evaluates it
-- once per statement instead of once per row.
-- -----------------------------------------------------------------------------
alter table public.vocabulary enable row level security;
alter table public.learning_events enable row level security;

-- vocabulary
create policy "vocabulary_select_own"
  on public.vocabulary for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "vocabulary_insert_own"
  on public.vocabulary for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "vocabulary_update_own"
  on public.vocabulary for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "vocabulary_delete_own"
  on public.vocabulary for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- learning_events
create policy "learning_events_select_own"
  on public.learning_events for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "learning_events_insert_own"
  on public.learning_events for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "learning_events_delete_own"
  on public.learning_events for delete
  to authenticated
  using ((select auth.uid()) = user_id);


-- -----------------------------------------------------------------------------
-- Function: record_answer
--
-- Atomically increments the counters, sets last_asked_at and writes a
-- learning event. Avoids lost updates when several devices answer at the
-- same time (no read-modify-write on the client).
--
-- Idempotent via p_event_id: calling it twice with the same id counts once.
-- Returns the updated vocabulary row, or NULL if the vocabulary no longer
-- exists (e.g. deleted on another device while the answer was queued).
-- -----------------------------------------------------------------------------
create or replace function public.record_answer(
  p_event_id uuid,
  p_vocabulary_id uuid,
  p_was_correct boolean,
  p_answered_at timestamptz default now()
)
returns public.vocabulary
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_answered_at timestamptz := least(coalesce(p_answered_at, now()), now());
  v_inserted integer;
  v_row public.vocabulary;
begin
  if v_user_id is null then
    raise exception 'not authenticated' using errcode = '42501';
  end if;

  perform 1 from public.vocabulary
   where id = p_vocabulary_id and user_id = v_user_id;
  if not found then
    return null;
  end if;

  insert into public.learning_events (id, user_id, vocabulary_id, was_correct, created_at)
  values (p_event_id, v_user_id, p_vocabulary_id, p_was_correct, v_answered_at)
  on conflict (id) do nothing;

  get diagnostics v_inserted = row_count;

  if v_inserted = 0 then
    -- Already recorded (retry): return the current state without counting again.
    select * into v_row from public.vocabulary
     where id = p_vocabulary_id and user_id = v_user_id;
    return v_row;
  end if;

  update public.vocabulary
     set correct_count   = correct_count   + case when p_was_correct then 1 else 0 end,
         incorrect_count = incorrect_count + case when p_was_correct then 0 else 1 end,
         last_asked_at   = greatest(coalesce(last_asked_at, v_answered_at), v_answered_at)
   where id = p_vocabulary_id and user_id = v_user_id
  returning * into v_row;

  return v_row;
end;
$$;

revoke all on function public.record_answer(uuid, uuid, boolean, timestamptz) from public, anon;
grant execute on function public.record_answer(uuid, uuid, boolean, timestamptz) to authenticated;
